### ISSUE TITLE
Inconsistent focus state on document list component

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#1193]
When the title in a document list goes onto a second line, the focus state then takes up the entire width of the parent element. This is due to `display` being set to `inline-block`.

This displays differently to a link on a single line, and when not focused there is an non-visible area on the right that can trigger the link.

<img width="309" alt="Screenshot 2019-11-08 at 11 09 45" src="https://user-images.githubusercontent.com/1732331/68472749-164ffc00-0219-11ea-8f36-4674c538ecf7.png">

A fix is to change `display` to `inline` - I've done quick check to see make sure that it works, but it needs further investigation for the use cases for this component.

**Comment by alex-ju** [comment]
The Design System team has a similar matter – [guidance on focus states](https://github.com/alphagov/govuk-design-system/issues/1853) – under their radar. The best action is to keep an eye on that progress, and ideally get involved with shaping it up.

**Comment by owenatgov** [comment]
Just having a look at this. I did some investigation just now and can't see any issue with removing the `inline-block` that Ian mentioned. Do we still want to hold off on this until the design system focus guidance is picked up?

**Comment by alex-ju** [comment]
The Desing System is aware of this and they will take this example into account when reviewing the focus state, but this shouldn't block us from fixing this. Ian's suggested fix, especially as you've tested it, is more than welcome to address this issue.

**Comment by owenatgov** [comment]
So, I've sadly found a problem after that positive message above. The reason that the link is set to `inline-block` is for instances of document lists [with contexts](https://components.publishing.service.gov.uk/component-guide/document_list/with_context). Removing the display so that it's just `inline` doesn't have a huge impact however it does change the appearance of context items on mobile.

### For screen size 336px
With inline block:
![Screenshot 2022-01-07 at 10 45 29](https://user-images.githubusercontent.com/64783893/148533020-5dd5f1d8-4ce4-45a6-a758-20a0e3978c07.png)

With inline:
![Screenshot 2022-01-07 at 10 46 00](https://user-images.githubusercontent.com/64783893/148533075-9a2752c4-12a3-4ced-92b9-9b887f6c37d3.png)

I'm having a think about how else to handle this. I'll also investigate the use of document lists with contexts.
