### ISSUE TITLE
[Accordion] Can't specify data items for individual sections

### ISSUE THREAD

**Issue by faissalMT** [alphagov/govuk_publishing_components#1285]
I'm trying to move an existing accordion to instead use this gem, however it seems that there is no way to set the data fields for the `<div>`s that hold each section, this makes testing them difficult:
![image](https://user-images.githubusercontent.com/41294831/74168527-ce7aaf80-4c21-11ea-9bec-1cf0f3810e3a.png)
Ordinarily we would place a `data-qa=` on each of these `<div>`s and pick them out that way, but there doesn't seem to be a way to do this, I would have expected to be able to do something like:
```
<%= render "govuk_publishing_components/components/accordion", {
  items: {
    heading: {
      text: "Section heading"
    },
    content: {
      html: sanitize("my text"),
      data_attributes: {
        qa: "accordion__section"
      }
    }
  }
}%>
```

**Comment by andysellick** [comment]
Thanks @faissalMT. You're welcome to use our gem if it's helpful to you but we don't currently have a support model for dealing with external queries. I'd suggest using another way to identify specific accordion sections within your tests, such as their content, rather than adding additional production code for testing.
