### ISSUE TITLE
Date of birth component should have autocomplete attributes

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#1392]
The date of birth component could have the following autocomplete attributes automatically added:

- "bday-day"
- "bday-month"
- "bday-year"

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by owenatgov** [comment]
Having a cursory glance at this, I'm presuming we're talking about [this](http://localhost:3212/component-guide/date_input)? It doesn't look like date of birth is the most common use for this component presently, however there also aren't any other autocomplete attributes that we could apply here. I see 2 approaches:

1. Apply the autocomplete attributes regardless of use, just so that something is there
2. Add an API attribute that adds the attributes if the component is being used as a DOB field

I'm leaning towards 2 but I'm interested to know your thoughts.

**Comment by injms** [comment]
That is a fair and true point - it's a date component, not a date of birth component.

I think option 2 is a better solution, as it'd be optional. My personal thought would be something that would turn it off and on with a boolean rather than setting each autocomplete attribute; for example:

```erb
<%= render "govuk_publishing_components/components/date_input", {
  date_of_birth_autocomplete: true,
} %>
```

**Comment by owenatgov** [comment]
This was also what I was thinking! Whoever finds the time first can have a go at this.

**Comment by 36degrees** [comment]
Worth flagging that it only makes sense to use those autocomplete values if the date you're asking for is the date of birth _of the person filling the form in_ – not if you're asking for someone else's date of birth.

Might be worth thinking about when documenting it.

**Comment by alex-ju** [comment]
The [Design System suggests using the autocomplete attribute](https://design-system.service.gov.uk/components/date-input/#use-the-autocomplete-attribute-for-a-date-of-birth) for things like date of birth.
