### ISSUE TITLE
Search component layout looks broken when JavaScript is disabled

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_publishing_components#1824]
Search component layout looks broken when JavaScript is disabled

![Screenshot 2020-12-11 at 16 00 16](https://user-images.githubusercontent.com/788096/102068634-979e9880-3df4-11eb-9d35-50a4e901b73b.png)
![Screenshot 2020-12-11 at 16 00 34](https://user-images.githubusercontent.com/788096/102068637-99685c00-3df4-11eb-8b7d-3422cb52ac05.png)

Reported by @edwardhorsford in the x-government Slack channel.

**Comment by andysellick** [comment]
This looks like it should be a simple fix - change the colour of the label, change the input (maybe) to be a bit more clearly defined.

However I remember there being some complexity around this. The label is normally positioned over the input and is hidden by JS when the input is clicked/focussed. There was a fix relating to when the page is viewed 'in order', where the label was gets moved above the input (regardless of CSS or JS) and was black text on a blue background (contrast fail) and there's no CSS/JS way of detecting that, which is why the label has a white background.

**Comment by OllieJC** [comment]
I've experienced this. Naïve fix - would setting the label's background to none and white text by default, and then set the background along with the text colour to the grey (as is currently) with the `js-enabled` class? 

I've got the following in my stylebot, that works:
```
.gem-c-search__label {
    background: #00000000 !important;
    color: #fff !important;
}
```

![Screenshot 2021-02-18 104820](https://user-images.githubusercontent.com/5426038/108346188-0a523880-71d7-11eb-819f-f111411eecde.png)

---

![Screenshot 2021-02-18 104855](https://user-images.githubusercontent.com/5426038/108346192-0aeacf00-71d7-11eb-805c-10fafc44098e.png)
