### ISSUE TITLE
"You've accepted all cookies" text included in the DOM when not correct

### ISSUE THREAD

**Issue by Nooshu** [alphagov/govuk_publishing_components#1892]
Running the homepage through the lynx browser using:

```
docker run --rm -it nbrown/lynx lynx www.gov.uk
```

We can see the text: 
"You've accepted all cookies. You can change your cookie settings at any time."

<img width="599" alt="Screenshot 2021-01-27 at 11 17 39" src="https://user-images.githubusercontent.com/1223960/105983900-4ccd9d00-6091-11eb-98c4-48106f3d1338.png">

This looks to be text that already exists in the DOM. I don't believe the cookies have actually been accepted (needs verification).

Although we don't support the Lynx browser, this is could still be reproducible in modern browsers when disabling CSS / JS. We could look into inserting this text into the DOM via JS once a user accepts.

**Comment by alex-ju** [comment]
We have a similar issue further down the page in the feedback component where we say "Thank you for your feedback" although they haven't interacted with the form. The [feedback problem also happens when JavaScript is disabled](https://github.com/alphagov/govuk_publishing_components/issues/1889, in comparison with the cookie banner, where the issue only appears when the styles are disabled.

**Comment by injms** [comment]
Lynx is not on the [list of supported browsers](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices) - however, this issue is replicable in modern browsers by turning off CSS:

<img src="https://user-images.githubusercontent.com/1732331/106125762-6c79c980-6154-11eb-98ab-b92251f5c198.png" width="600px" alt="">

As JavaScript is still enabled, the banner will still set cookies and change state by hiding some of the cookie banner with inline styles:

<img src="https://user-images.githubusercontent.com/1732331/106126005-bf538100-6154-11eb-8125-984ef0172282.png" width="600px" alt="">

Turning inline styles off will cause the whole banner to be shown:

<img src="https://user-images.githubusercontent.com/1732331/106126135-ea3dd500-6154-11eb-8aad-a82b93eba0cd.png" width="600px"  alt="">

I haven't tested this in a screenreader with the styles turned off.

**Comment by alex-ju** [comment]
This issue has been solved in the new cookie banner implementation. See lynx example below.

<img width="560" alt="Screenshot 2021-04-12 at 19 54 08" src="https://user-images.githubusercontent.com/788096/114446351-0d5f1900-9bc9-11eb-9e96-8128fd33fc60.png">
