### ISSUE TITLE
Navigation items misaligned on Layout super nav component

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_publishing_components#2331]
https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header

The "Departments" text is 1px misaligned with the two drop downs either side of it:

![Screenshot 2021-09-30 at 17 00 39](https://user-images.githubusercontent.com/319055/135492147-a0b7223c-b2f9-430c-91e1-2cdf3ed7ffe9.png)

There’s also a 1px misalignment on the search box toggle when open and focused vs closed and focused (note the black bar on the X image):
![Screenshot 2021-09-30 at 17 08 09](https://user-images.githubusercontent.com/319055/135492415-f392e565-7fd3-4902-8f59-9fffb8996b91.png)
![Screenshot 2021-09-30 at 17 08 06](https://user-images.githubusercontent.com/319055/135492421-217d5bf0-a804-40c4-9eb8-0befe4abf8ef.png)

**Comment by injms** [comment]
Firstly, thanks for reporting these visual issues.

The misalignment of "Departments" should hopefully be fixed in the coming week or so.

The black line on the button is deliberately placed to differentiate between the cookie banner and open section:

![image](https://user-images.githubusercontent.com/1732331/135508946-d83a0278-af38-481a-af0e-f6948b78a6a9.png)

This small border isn't an ideal solution - it's going to be iterated on to find something that doesn't look so glitchy when the cookie banner isn't present but doesn't make the cookie banner and an open section look connected.

**Comment by injms** [comment]
I'm closing this as the alignment was fixed in https://github.com/alphagov/govuk_publishing_components/pull/2401 - which has now been [released in the gem](https://github.com/alphagov/govuk_publishing_components/pull/2403) and then [bumped in the application that renders the header](https://github.com/alphagov/static/pull/2639).
