### ISSUE TITLE
Printing pages with organisation logos can have a overly large logo

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2374]
## Problem 

If an organisation has a non-crest, custom image logo it will be printed out at it's unresized dimensions - this can lead to a logo being surprisingly large. For example, on a [page with the Environment Agency page][eg]:

![](https://user-images.githubusercontent.com/1732331/137738586-8eafe95e-50fb-41d4-a6fd-9a6109df7799.png)

## Expected behaviour

The logo should be small, which is more in keeping with the screen version of the page, and doesn't overwhelm the layout.

[eg]:https://www.gov.uk/government/publications/social-distancing-when-signing-and-handing-over-waste-transfer-and-consignment-notes-in-person-rps-c8/social-distancing-when-signing-and-handing-over-waste-transfer-and-consignment-notes-in-person-rps-c8

**Comment by patrickpatrickpatrick** [comment]
Did some looking around it seems that the width of the logo is set by `organisation-logos__logo` which is here https://github.com/alphagov/government-frontend/blob/main/app/assets/stylesheets/helpers/_organisation-logos.scss I was wondering if that meant that the print style should be added in that repo instead of this one @andysellick ?

**Comment by andysellick** [comment]
Those styles apply to the wrappers for the component but the image is part of the component, so I think this should be handled at the component level.
