### ISSUE TITLE
Navigation header and accordion use unprefixed `transform` CSS

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#2419]
On IE9 the new site header looks like this:

![Screenshot 2021-11-05 at 09 24 19](https://user-images.githubusercontent.com/861310/140488372-d377e14e-db43-4666-9576-f8b232ac7863.png)

The 'down' chevrons next to the menu items don't quite look right because it's a pseudo element styled with a partial border and rotated in CSS to look like an arrow. For some reason IE9 doesn't seem to be picking up on that - it doesn't seem to be listing the `transform` property in its inspector.

Not sure how concerned we are with minor visual problems on old browsers we don't really support, but thought it worth pointing out.

**Comment by 36degrees** [comment]
> Unfortunately [IE9 doesn't support rotate](https://caniuse.com/mdn-css_properties_rotate) so it isn't rotated.

I think the `rotate` CSS property is relatively new (part of [CSS Transforms Module Level 2](https://drafts.csswg.org/css-transforms-2/#individual-transforms)) and only works in Safari and Firefox – the rotation looks to be done using `transform: rotate` which is supported in IE9, so I don't think that's the issue here. For example, the checkmark in checkboxes uses the same technique and that definitely does work in IE9 – but not in IE8, where we fall back to 'native' checkbox controls.

**Comment by andysellick** [comment]
Thanks @36degrees, have updated the description. Not exactly sure what's causing this then. Maybe IE9 doesn't like multiple properties in `transform`?

**Comment by injms** [comment]
Worth noting that the same chevron technique is used for the accordion as well, so is also an issue there - 
<img width="891" alt="Screenshot 2021-11-08 at 09 56 28" src="https://user-images.githubusercontent.com/1732331/140721803-41ca30d4-86aa-4fed-b4cb-694ec0e266b2.png">

**Comment by 36degrees** [comment]
Ah, it looks like the `transform` property in IE9 needs to be vendor-prefixed.

We run autoprefixer on GOV.UK Frontend, so [the 'built' CSS includes all the required prefixes](https://github.com/alphagov/govuk-frontend/blob/33de1753ea7a0f03be164725f50bf115647b7d00/package/govuk/components/checkboxes/_index.scss#L104-L108).
