### ISSUE TITLE
Search component button not responding to browser default font size changes

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#2572]
## Problem
When a user sets a different default font size in their browser, the [search component](https://components.publishing.service.gov.uk/component-guide/search) does not grow/shrink in response properly. Example:

### Not growing
<img width="1033" alt="Screenshot 2022-01-19 at 16 21 03" src="https://user-images.githubusercontent.com/64783893/150172162-973d425c-7ed4-4d85-95aa-e1751675b93d.png">

### Not shrinking
<img width="1008" alt="Screenshot 2022-01-19 at 16 21 12" src="https://user-images.githubusercontent.com/64783893/150172189-01f031a8-94fb-46ff-8459-0146453692f3.png">

This can be reproduced on Chrome and Firefox using the following methods:

- **Chrome**: Settings -> Appearance -> Font size
- **Firefox**: Settings -> Language and Appearance -> set "Size" to something other than 16 and refresh

## Proposal
This can be fixed by either adding a set of `em` widths and heights or replacing the default `px` value (`40`) with an `em` value.

**Comment by maxgds** [comment]
Isn't that expected behaviour? The whole point is that people want to enlarge text but not pictures and icons etc, isn't it? Otherwise they'd zoom. Do we have other examples where icons do respond to font size change?

**Comment by maxgds** [comment]
I'm also on the fence. To my mind it's behaving as expected and while we can adjust for it - should we? If we should, where do we draw the line? We could measure everything in ems and make it all scale but then you've just reimplemented zoom and users presumably have a reason for not using that technique. It looks pretty horrible as it stand, it's true, but so will vast amounts of the web, probably including chunks of our own site. I think it comes down to "Is it still usable?" and would conclude "yes" and no action is needed. If the grown text was obscuring the button it I'd see that as a bug that needed attention, but not this. You could argue that the input shouldn't grow either, but that's fundamentally related to text and it needs to in order to work. I'm not wedded to this 100%, can definitely be convinced, but if we do decide to address it I think it needs to become a larger piece of work where we decide and document how to apply the fix and what elements of a web page we expect to adjust alongside text-only scaling.

**Comment by andysellick** [comment]
Is this issue a duplicate of https://github.com/alphagov/govuk_publishing_components/issues/2498 ?

**Comment by owenatgov** [comment]
@maxgds This is valuable discourse. I do agree that there is a line to be drawn here around how much we commit to em-ifying everything. I don't for example think we should apply this to other buttons. I _do_ think it's worth doing here as it creates a visual discrepancy and messes with the visual harmony of govuk based on this specific design where the implied visual behaviour is the button sitting next to the input as a single entity. The input is changing shape in response to the text size, which makes sense since an input's size is intrinsically tied to it's font size, I concede that it's still usable so it's not a critical bug, but I also assert that the lack of visual consistency could be disturbing to users and impact their good will. I'm now getting into UX so I wonder if it's worth bringing a designer in to assess this, at least how urgent it is.

@andysellick It is! I'm gonna close this but I'll leave a comment linking to this issue on your one as I think there's a lot of useful discussion going on here.

**Comment by maxgds** [comment]
I'm pretty sure that a designer looking at it will be horrified and insist we fix it. So make sure they see a representative sample of the rest of the site and decide how far this fixing should go!
