### ISSUE TITLE
Automate upgrades of vendored Speedcurve Lux JS library

### ISSUE THREAD

**Issue by bilbof** [alphagov/govuk_publishing_components#2633]
Currently our in-hours on call rota has a critical alert because this library has had a new version released, as a result of https://github.com/alphagov/govuk-puppet/pull/11339.

To resolve the alert we would need to upgrade the vendored code to use the latest version. A previous upgrade as an example: https://github.com/alphagov/govuk_publishing_components/pull/2152.

The 2nd line developers are not the appropriate team to upgrade this dependency. It would be better to find a service/team-specific alternative approach to raising an alert at the platform level. For instance, we could investigate using Dependabot or similar.

**Comment by andysellick** [comment]
[Recent events](https://github.com/alphagov/govuk_publishing_components/pull/3592) have made me skeptical that an automated upgrade system is possible, due to the complexity and changing nature of this code. I'm tempted to close this issue as unsolvable.

On the brighter side, the git repo for this code has been made public: https://github.com/SpeedCurve-Metrics/lux.js so anyone can now watch the repo for any new releases.

Also we have tool running in slack in #user-experience-measurement-govuk-robot-invasion that notifies us when a new version is ready.

**Comment by andysellick** [comment]
As previously mentioned, I don't think automating this is possible, so I'm closing this issue.
