### ISSUE TITLE
Remove govuk_app_config

### ISSUE THREAD

**Issue by willfish** [alphagov/govuk_publishing_components#2680]
I'm interested to know why this gem has a hard dependency on the govuk_app_config gem?

This is for projects rather than libraries AFAIK.

Is there any good reason why we can't remove it?

**Comment by maxgds** [comment]
GOV.UK frontend apps and this gem are really closely intertwined, it's not a general purpose gem like most libraries. This dependency was introduced to avoid duplicating config that would otherwise have to be updates in two places in parallel and at the time it linked to the taxonomy sidebar links shown in the related nav component (https://components.publishing.service.gov.uk/component-guide/related_navigation). I couldn't say for certain whether we're relying on it now for other config related stuff, but it doesn't seem likely it could easily be extracted. (btw, hi!)

**Comment by willfish** [comment]
I figured there was a good reason for it. Thanks Max! (also hi!)
