### ISSUE TITLE
Lux.js beacon mode is no longer supported

### ISSUE THREAD

**Issue by ollietreend** [alphagov/govuk_publishing_components#2717]
The most recent version of [Lux.js (v300) dropped support](https://support.speedcurve.com/changelog/rum-update-luxjs-v300) for the `LUX.beaconMode = 'simple'` configuration option. This means that Lux will no longer use 'simple' `<img>` beacons, but will instead load remote JavaScript via `<script>` tags to record beacon activity.

As explained in our own documentation on Real User Metrics' [Beacon mode](https://github.com/alphagov/govuk_publishing_components/blob/3674bf941cacbe97161f29ed63a349467d720eb2/docs/real-user-metrics.md#beacon-mode), the Content Security Policy on GOV.UK needs to be changed to allow Lux's `<script>` tags to be embedded into the page.

The [recommended Content Security Policy for SpeedCurve RUM](https://support.speedcurve.com/docs/add-rum-to-your-csp) is:

```
script-src: cdn.speedcurve.com; 
img-src: lux.speedcurve.com;
connect-src: lux.speedcurve.com;
```

This is going to require changes both in this repository (to update our [Beacon mode](https://github.com/alphagov/govuk_publishing_components/blob/3674bf941cacbe97161f29ed63a349467d720eb2/docs/real-user-metrics.md#beacon-mode) documentation) and in [govuk_app_config](https://github.com/alphagov/govuk_app_config/blob/87e445eccee5fba2449a170d5ba628e8a380fcb8/lib/govuk_app_config/govuk_content_security_policy.rb#L29-L38).

**Comment by ollietreend** [comment]
@kevindew I [couldn't find any evidence](https://github.com/search?q=org%3Aalphagov+beaconMode&type=code) of it being explicitly configured. Which confused me somewhat. 🤷🏻‍♂️

**Comment by injms** [comment]
The `beaconMode` configuration was removed when the self hosted version [was updated to v300](https://github.com/alphagov/govuk_publishing_components/pull/2637) - which is why is isn't findable any more.

From looking at the code and talking to the devs at SpeedCurve, the (self hosted) script now uses images by default - which is why the setting was removed. For example:

https://github.com/alphagov/govuk_publishing_components/blob/b3e8fd8911b5dd98d4c056c9fb3fe133231bcd40/app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js#L1547-L1549

We self host the main script that sends the information to Speedcurve (`lux-reporter.js`) - so as Kevin said, the configuration in the Speedcurve docs needs tweaking for our use case. I think this is where the confusion around loading remote JavaScript is coming from.
