### ISSUE TITLE
Bug in the appearance of documents lists due to a top border in every list item

### ISSUE THREAD

**Issue by kubabartwicki** [alphagov/govuk_publishing_components#3083]
Hello

A few designers from GOV.UK have been exploring whether we can be more proactive in fixing some quirks in the appearance of GOV.UK. This issue is about one of them, which is a bug in the appearance of a top border in a documents list, most visible in specialist finders, like [this one](https://www.gov.uk/animal-disease-cases-england).

I think a solution to this can be about removing the top border from the first child of a document list. You can do that [in this file](https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss) by adding this line:

`.gem-c-document-list__item:first-child { 
  border-top: none; 
}`

I'm not sure how widely this component is used so am not able to fully assess the impact of the change, but have looked at it in the specialist finder and search results and the change improves the appearance. See attached. 
***
<img width="1036" alt="after-change-search-results" src="https://user-images.githubusercontent.com/902580/204017011-485c3bbe-5ad6-42c7-8af1-dd12304823f3.png">

Search results after top border removed from first list item

***
<img width="1014" alt="after-change-specialist-finder" src="https://user-images.githubusercontent.com/902580/204017018-d60e9a01-b55f-410d-8e5f-f86258253f8d.png">

Specialist finder after top border removed from first list item

**Comment by kevindew** [comment]
Nice one, bringing this up and looking at this. It's a bug bear of mine.

As I understand it's not quite as simple as turning off the item on first child as we want it in cases where we have filters. For example: https://www.gov.uk/search/news-and-communications. So I imagine if we removed it from first child we'd need to add a border bottom to the sort options

There is modifier that can remove the top border: https://components.publishing.service.gov.uk/component-guide/document_list#without_top_border_on_list_element. So I think we can actually fix this in the app that calls this, finder-frontend, by setting the first item in the list to have the remove_top_border option if there are no filters. 

However applying that to Finder Frontend looks like a couple of hurdles. I think we'd have to tell a search result it shouldn't have a top border in Ruby. Something like:

```
  def document_list_component_data(documents_to_convert:)
    has_sort_options = sort_presenter.to_hash.present

    documents_to_convert.map.with_index do |document, index|
      SearchResultPresenter.new(
        document: document,
        rank: index + 1,
        metadata_presenter_class: metadata_presenter_class,
        doc_count: documents.count,
        facets: facets,
        content_item: content_item,
        debug_score: debug_score,
        include_ecommerce: include_ecommerce,
        remove_top_border: index == 0 && !has_sort_options,
      ).document_list_component_data
    end
  end
```

in: https://github.com/alphagov/finder-frontend/blob/6a39a0f40cb94e7d001c1132ad12331e68083ab1/app/presenters/result_set_presenter.rb#L57-L70

I'm not sure quite which team own Finder Frontend, but I'll ping @andysellick who's a fountain of frontend knowledge, as to whether he thinks it should be fixed with changes to components or changes to how apps use them.

**Comment by kubabartwicki** [comment]
Woop, thanks Kevin. For what it's worth, I think that even on pages with filters, removing a top border would look fine. But it sounds like it might make no difference to the implementation anyway.

**Comment by chao-xian** [comment]
@kevindew it's @maxgds 's team

**Comment by andysellick** [comment]
> I'm not sure quite which team own Finder Frontend, but I'll ping @andysellick who's a fountain of frontend knowledge, as to whether he thinks it should be fixed with changes to components or changes to how apps use them.

Great digging @kevindew. Sounds like it needs to be something handled by the application rather than the component.

I thought our team was responsible for `finder-frontend` but Kelv's saying it's not, so I don't know.

**Comment by maxgds** [comment]
You were right, Andy, it's your team's if it's finder-frontend: https://docs.publishing.service.gov.uk/repos/finder-frontend.html - not sure why Kelv thought it was us.
