### ISSUE TITLE
Header search button still shows divider line when activated

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk_publishing_components#3087]
I'm getting a grey divider crashing into the opened search button on mobile, which looks a bit buggy:

![IMG_3319](https://user-images.githubusercontent.com/19834460/204021871-060443d4-f924-439c-9e95-b247cc1bd401.jpg)

This is on Safari on an iPhone with iOS 16.

I think it should probably just not show the divider when the menu's open – that's how the other 'menu' button behaves.

**Comment by jon-kirwan** [comment]
I think this might have been resolved by various changes in PR https://github.com/alphagov/govuk_publishing_components/pull/3058. Can anyone please confirm?

**Comment by monicacrusellasfanlo** [comment]
@jon-kirwan did you find out if this has been resolved? Thank you!

**Comment by patrickpatrickpatrick** [comment]
https://github.com/alphagov/govuk_publishing_components/pull/3201 Hello, this should be resolved by this PR

**Comment by hannalaakso** [comment]
Just a note to say that I'm not seeing this happening on the current live site in Safari iOS 16 so I think it might have already been fixed by https://github.com/alphagov/govuk_publishing_components/pull/3058. Tempted to close the issue but maybe someone else could double check if they can't replicate it before I do that?

**Comment by patrickpatrickpatrick** [comment]
This has been resolved by https://github.com/alphagov/govuk_publishing_components/pull/3201, but I didn't close this issue! Sorry!
