### ISSUE TITLE
Why do not all pages have ‘print’ buttons?

### ISSUE THREAD

**Issue by ChristineWuerth** [alphagov/govuk_publishing_components#4266]
This is an inconsistency someone raised with us in the process of documenting the print link component as part of the design documentation work:
Not all pages have ‘print’ buttons. Why do some pages have it and others don’t?

**Comment by jon-kirwan** [comment]
Hi @ChristineWuerth - not all pages require the print button, but it's commonly used for page types like guides, detailed guides, HTML publications, or manuals. The decision to add print buttons to other pages would be made by the teams managing those specific applications (and their respective pages and document types) if they see a benefit in doing so. Since this isn't something to address in this repository, I'll go ahead and close this issue for now
