### ISSUE TITLE
Possible regression with text colour in 12.0.0

### ISSUE THREAD

**Issue by cbaines** [alphagov/govuk_publishing_components#572]
There were some problems with the finder frontend upgrade to 12.0.0. https://github.com/alphagov/finder-frontend/pull/629#issuecomment-428524782

# Previous
![good](https://user-images.githubusercontent.com/1130010/46730921-da92dd80-cc78-11e8-9ba6-caef6b2e142b.png)
# 12.0.0
![bad](https://user-images.githubusercontent.com/1130010/46730920-da92dd80-cc78-11e8-9984-1c9d1ba08d69.png)

**Comment by alex-ju** [comment]
Thanks for raising this @cbaines. Will look into it.

**Comment by alex-ju** [comment]
@cbaines unfortunately I have trouble deploying this locally; it's raising a Nokogiri error in slimmer. Will try to overcome this 🤞

**Comment by cbaines** [comment]
This also looks to affect Manuals Frontend as well, I'm guessing it's a similar issue.

![integration-vs-production-manuals-frontend](https://user-images.githubusercontent.com/1130010/46875722-01454580-ce2c-11e8-80b2-940c63979ea2.png)

**Comment by alex-ju** [comment]
12.0.0 introduces implicit colour for any text to ensure isolation (in this example, black) which was causing the issues presented above.

There is an `inverse` option for components (in our case breadcrumb and title) that we can use to ensure negative colour (white text) for the components used in these pages.

The first example was fixed by https://github.com/alphagov/finder-frontend/pull/633/files. I'll look and update the code for the second example.

I'll leave this issue open for a while, in case other people are running into this issue while upgrading to this major release.

**Comment by cbaines** [comment]
Great, thanks Alex for the information and looking in to this :)

**Comment by tijmenb** [comment]
I think this is fixed now, 12.0.0 has been on production for a week and no new issues have surfaced.
